<template>
  <div>
      <div class="uk-container-expand ">
         <div class="uk-card uk-card-small uk-card-default uk-card-body uk-padding-remove-bottom wi-recharge-topnav">
            <a @click="$router.go(-1)" uk-icon="icon: arrow-left; ratio: 1.2" class="uk-align-left uk-margin-remove-adjacent wi-back-icon uk-icon"><svg width="24" height="24" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" data-svg="arrow-left"><polyline fill="none" stroke="#000" points="10 14 5 9.5 10 5"></polyline><line fill="none" stroke="#000" x1="16" y1="9.5" x2="5" y2="9.52"></line></svg></a>
            <p class="wi-text-large uk-margin-large-right">Privacy Policy</p>
         </div>
      </div>
      <div class="uk-section uk-section-default uk-padding-remove uk-margin-large-bottom ">
         <div class=" uk-margin-auto  uk-margin-small-bottom ">
            <div class="uk-card uk-card-body uk-width-1-1">
               <!-- <h3 class="uk-card-title wi-text-large">Company Introduction </h3> -->
               <p class="uk-text-justify">This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require 
                  any physical or digital signatures to make the terms of this policy binding.
               </p>
               <p class="uk-text-justify">At Our shop sites data protection is a matter of trust and your privacy is very important to us. We use your personal information only in the manner set out in this Privacy Policy. Please read this privacy policy to learn more about our information gathering and dissemination practices.</p>
               <p class="uk-text-justify">The privacy practices of this statement apply to our services available under the domain and sub-domains of Our shop sites (the "Site") and apply generally to our parent, affiliates, subsidiaries or joint venture websites. By visiting the Site you agree to be bound by the terms and conditions of this Privacy Policy.</p>
            </div>
         </div>
      </div>
  </div>
</template>